name: WeebX Clang

on:
  push:
  schedule:
    - cron: '0 0 * * *'

env:
    GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
  
jobs:
  latest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Building latest
      run: |
        git clone -b new-clang https://github.com/XSans0/script
        cd script
        bash goBuild latest

#  good-revision:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v3
#    - name: Building good revision
#      env:
#        GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
#      run: |
#        git clone -b new-clang https://github.com/XSans0/script
#        cd script
#        bash goBuild gr

  fourteen:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Building 14.x
      env:
        GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
      run: |
        git clone -b new-clang https://github.com/XSans0/script
        cd script
        bash goBuild 14