name: WeebX Clang
on:
  push:
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Go Build
      env:
        GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
      run: |
        git clone -b weebx https://github.com/XSans02/my-script script
        cd script
        bash ci.sh deps
        bash goBuild
