name: XSansTC Clang

on: 
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    container: 
      image: zycromerz/kerneldocker:v3

    steps:
    - uses: actions/checkout@v2
    - name: Clang Builder
      env:
        LLVM_NAME: ${{ secrets.LLVM_NAME }}
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        GH_USERNAME: ${{ secrets.GH_USERNAME }}
        GH_EMAIL: ${{ secrets.GH_EMAIL }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        GH_PUSH_REPO_URL: ${{ secrets.GH_PUSH_REPO_URL }}
        TYPE: ${{ secrets.TYPE }}
      run: |
        apt-get install -y cmake curl git ninja-build
        git clone -b clang https://github.com/XSans02/my-script script
        cd script
        bash goBuild
