name: WeebX Clang

on:
  workflow_dispatch:

env:
    GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
  
jobs:
  Build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Good Revision
      run: |
        git clone -b master https://github.com/XSans0/clang-build script
        cd script
        bash build.sh
