name: XSansTC Clang
on:
  push:
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Start Building
      env:
        GIT_MAIL: ${{ secrets.GIT_MAIL }}
        GIT_PASS: ${{ secrets.GIT_PASS }}
        GIT_REPO_URL: ${{ secrets.GIT_REPO_URL }}
        GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
      run: |
        git clone -b new-clang https://github.com/XSans02/my-script script
        cd script
        bash goBuild
