name: WeebX Clang

on: 
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Go Build
      env:
        GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
      run: |
        git clone -b new-clang https://github.com/XSans02/my-script script
        cd script
        bash goBuild
