name: XSansTC Clang
on:
  push:
  schedule:
    - cron: '* */6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Start Building
      env:
        LLVM_NAME: ${{ secrets.LLVM_NAME }}
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        GH_USERNAME: ${{ secrets.GH_USERNAME }}
        GH_EMAIL: ${{ secrets.GH_EMAIL }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        GH_PUSH_REPO_URL: ${{ secrets.GH_PUSH_REPO_URL }}
        TYPE: ${{ secrets.TYPE }}
        REAL_CHANNEL: ${{ secrets.REAL_CHANNEL }}
      run: |
        git clone -b clang https://github.com/XSans02/my-script script
        cd script
        bash ci.sh
        bash goBuild
