name: WeebX Clang Latest

on:
  push:
  schedule:
    - cron: '0 0 * * *'

env:
    GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
    TELEGRAM_CHAT: ${{ secrets.TELEGRAM_CHAT }}
    TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
    BRANCH: main
  
jobs:
  goBuild:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Building
      run: |
        git clone -b main https://github.com/XSans0/clang-build script
        cd script
        sudo apt update && sudo apt upgrade
        bash ci.sh deps
        bash build.sh